-- 啟用 UUID 擴充功能
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ==========================================
-- 1. 使用者與權限模組
-- ==========================================

-- Table: USER
CREATE TABLE "user" (
    user_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_name VARCHAR(20) NOT NULL UNIQUE,
    password VARCHAR(60) NOT NULL, -- Bcrypt Hash
    email VARCHAR(50) NOT NULL UNIQUE,
    status VARCHAR(10) NOT NULL CHECK (status IN ('Active', 'Disabled'))
);

-- Table: USER_ROLE
CREATE TABLE user_role (
    user_id UUID NOT NULL,
    role VARCHAR(10) NOT NULL CHECK (role IN ('User', 'Admin')),
    PRIMARY KEY (user_id, role),
    FOREIGN KEY (user_id) REFERENCES "user"(user_id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- ==========================================
-- 2. 冰箱與庫存管理模組
-- ==========================================

-- Table: FRIDGE
CREATE TABLE fridge (
    fridge_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    fridge_name VARCHAR(30) NOT NULL
);

-- Table: FRIDGE_ACCESS
CREATE TABLE fridge_access (
    user_id UUID NOT NULL,
    fridge_id UUID NOT NULL,
    access_role VARCHAR(10) NOT NULL CHECK (access_role IN ('Owner', 'Member')),
    PRIMARY KEY (user_id, fridge_id),
    FOREIGN KEY (user_id) REFERENCES "user"(user_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (fridge_id) REFERENCES fridge(fridge_id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Table: INGREDIENT
CREATE TABLE ingredient (
    ingredient_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    standard_unit VARCHAR(10) NOT NULL CHECK (standard_unit IN ('g', 'ml', 'pcs')),
    shelf_life_days INT NOT NULL CHECK (shelf_life_days > 0)
);

-- Table: FRIDGE_ITEM
CREATE TABLE fridge_item (
    fridge_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fridge_id UUID NOT NULL,
    ingredient_id BIGINT NOT NULL,
    quantity DECIMAL(10, 2) NOT NULL CHECK (quantity >= 0),
    entry_date DATE NOT NULL,
    expiry_date DATE NOT NULL,
    FOREIGN KEY (fridge_id) REFERENCES fridge(fridge_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ingredient_id) REFERENCES ingredient(ingredient_id) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- ==========================================
-- 3. 供應鏈與採購模組
-- ==========================================

-- Table: PARTNER
CREATE TABLE partner (
    partner_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    partner_name VARCHAR(50) NOT NULL,
    contract_date DATE NOT NULL,
    avg_shipping_days INT NOT NULL CHECK (avg_shipping_days > 0),
    credit_score INT NOT NULL CHECK (credit_score BETWEEN 0 AND 100)
);

-- Table: EXTERNAL_PRODUCT
CREATE TABLE external_product (
    external_sku VARCHAR(50) NOT NULL,
    partner_id BIGINT NOT NULL,
    ingredient_id BIGINT NOT NULL,
    product_name VARCHAR(100) NOT NULL,
    current_price DECIMAL(10, 2) NOT NULL CHECK (current_price > 0),
    selling_unit VARCHAR(20) NOT NULL,
    PRIMARY KEY (external_sku),
    FOREIGN KEY (partner_id) REFERENCES partner(partner_id) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (ingredient_id) REFERENCES ingredient(ingredient_id) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Table: SHOPPING_LIST_ITEM
CREATE TABLE shopping_list_item (
    user_id UUID NOT NULL,
    ingredient_id BIGINT NOT NULL,
    quantity_to_buy DECIMAL(10, 2) NOT NULL CHECK (quantity_to_buy > 0),
    added_date DATE NOT NULL,
    PRIMARY KEY (user_id, ingredient_id),
    FOREIGN KEY (user_id) REFERENCES "user"(user_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ingredient_id) REFERENCES ingredient(ingredient_id) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Table: STORE_ORDER
CREATE TABLE store_order (
    order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    partner_id BIGINT NOT NULL,
    order_date TIMESTAMP NOT NULL,
    expected_arrival DATE, -- Derived from order_date + partner.avg_days
    total_price DECIMAL(10, 2) NOT NULL CHECK (total_price >= 0),
    order_status VARCHAR(15) NOT NULL CHECK (order_status IN ('Pending', 'Paid', 'Shipped', 'Delivered', 'Cancelled')),
    FOREIGN KEY (user_id) REFERENCES "user"(user_id) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (partner_id) REFERENCES partner(partner_id) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Table: ORDER_ITEM
CREATE TABLE order_item (
    order_id BIGINT NOT NULL,
    external_sku VARCHAR(50) NOT NULL,
    partner_id BIGINT NOT NULL, -- Keep consistent with STORE_ORDER
    quantity INT NOT NULL CHECK (quantity > 0),
    deal_price DECIMAL(10, 2) NOT NULL, -- Snapshot price
    PRIMARY KEY (order_id, external_sku),
    FOREIGN KEY (order_id) REFERENCES store_order(order_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (external_sku) REFERENCES external_product(external_sku) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- ==========================================
-- 4. 食譜與計畫模組
-- ==========================================

-- Table: RECIPE
CREATE TABLE recipe (
    recipe_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id UUID NOT NULL,
    recipe_name VARCHAR(100) NOT NULL,
    cooking_time INT CHECK (cooking_time > 0),
    status VARCHAR(10) NOT NULL CHECK (status IN ('Pending', 'Approved')),
    FOREIGN KEY (owner_id) REFERENCES "user"(user_id) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Table: RECIPE_REQUIREMENT
CREATE TABLE recipe_requirement (
    recipe_id BIGINT NOT NULL,
    ingredient_id BIGINT NOT NULL,
    quantity_needed DECIMAL(10, 2) NOT NULL CHECK (quantity_needed > 0),
    PRIMARY KEY (recipe_id, ingredient_id),
    FOREIGN KEY (recipe_id) REFERENCES recipe(recipe_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ingredient_id) REFERENCES ingredient(ingredient_id) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Table: RECIPE_STEP
CREATE TABLE recipe_step (
    recipe_id BIGINT NOT NULL,
    step_number INT NOT NULL CHECK (step_number > 0),
    description VARCHAR(1000) NOT NULL,
    PRIMARY KEY (recipe_id, step_number),
    FOREIGN KEY (recipe_id) REFERENCES recipe(recipe_id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Table: RECIPE_REVIEW
CREATE TABLE recipe_review (
    user_id UUID NOT NULL,
    recipe_id BIGINT NOT NULL,
    rating INT NOT NULL CHECK (rating BETWEEN 1 AND 5),
    comment VARCHAR(500),
    review_date TIMESTAMP NOT NULL,
    PRIMARY KEY (user_id, recipe_id),
    FOREIGN KEY (user_id) REFERENCES "user"(user_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (recipe_id) REFERENCES recipe(recipe_id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Table: MEAL_PLAN
CREATE TABLE meal_plan (
    plan_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    recipe_id BIGINT NOT NULL,
    planned_date TIMESTAMP NOT NULL,
    FOREIGN KEY (user_id) REFERENCES "user"(user_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (recipe_id) REFERENCES recipe(recipe_id) ON DELETE CASCADE ON UPDATE CASCADE
);
